# 1、池化层

实现池化层的正向传播

In [6]:
import torch
from torch import nn
from d2l import torch as d2l

def pool2d(X,pool_size,mode='max'):          #对X层做 （pool_ize）的池化；最大池化或者平均池化      
    p_h,p_w =pool_size                       #拿到池化核的高和宽
    Y = torch.zeros((X.shape[0]-p_h+1,X.shape[1]-p_w+1))      #没有pad和stride;限值了遍历下标，也不会越界
    for i in range(Y.shape[0]):                                
        for j in range(Y.shape[1]):                              
            if mode == 'max':
                Y[i,j] = X[i:i+p_h,j:j+p_w].max()               
            elif mode == 'avg':
                Y[i,j] = X[i:i+p_h,j:j+p_w].mean()
    return Y

验证最大池化的输出

In [7]:
X = torch.tensor([[0.0,1.0,2.0],[3.0,4.0,5.0],[6.0,7.0,8.0]])
pool2d(X,(2,2))

tensor([[4., 5.],
        [7., 8.]])

验证平均池化

In [8]:
pool2d(X,(2,2),'avg')

tensor([[2., 3.],
        [5., 6.]])

## 1.2、填充和步幅

In [9]:
X = torch.arange(16,dtype=torch.float32).reshape((1,1,4,4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

直接调用torch中的maxpooling ；框架中步幅和池化窗口大小相同

In [11]:
pool2d = nn.MaxPool2d(2)      #3是3 * 3的窗口 ；torch中窗口和窗口是不会重合的
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

填充和步幅可以手动设定

In [12]:
pool2d = nn.MaxPool2d(3,padding=1,stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

设定一个任意大小的矩阵池化窗口，并分别设定填充的步幅的高度和宽度

In [13]:
pool2d = nn.MaxPool2d((2,3),padding=(1,1),stride=(2,3))
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

## 1.3、池化层在每个通道上单独运算

In [17]:
X = torch.cat((X,X+1),1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [18]:
pool2d = nn.MaxPool2d(3,padding=1,stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])